# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57f3bff3caa3b50e04c678d337fab9355147a361b98620e7bfadb04103111fab9c91636ae396b8c6af96648d7aee15c9fe4e33003ca65a0ac18b9c5b15cc95cf

test:
  secret_key_base: 0a83e12b0b52398308677e7d9ea1fdadec21f25612261d59ce4de7fb2f1c81623cedaa1c2fd3230ea35a56ea8ec61339cc1ab5b53c3d00ffd40f25b430e2aeb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
